#!/bin/sh

# Include
. ./constants

##############################################
# Name            :
# Description     :
# Returns         :
##############################################
function CheckUmask(){
  umask $UMASK_OPTION
  if [ $? -eq 0 ]; then
       echo -e "${OK} [*] Setting umask to ${UMASK_OPTION} ${NORMAL}"
     else
       echo -e "${WARNNING} [x] Could not set umask ${NORMAL}"
  fi
}

##############################################
# Name            :
# Description     :
# Returns         :
##############################################
function MyUser(){
  IM=`whoami`
  if [ "${IM}" = "" ]; then
      echo -e '\033[1;31m [x] Could  not determine user \033[0m'
  fi
  if [ "${IM}" = "root" ]; then 
      echo -e '\033[1;31m [x] This programm should not be executed as root \033[0m'
  fi
}

##############################################
# Name            :
# Description     :
# Returns         :
##############################################
function BuildDir(){
  BUILDDIR="/opt/HashId-SecScan"
  if [ ! -d ${BUILDDIR} ]; then
      echo -e "\033[1;31m [x] { ${BUILDDIR}} not found \033[0m"
      echo -e "\033[1;33m  Hint:  Create it with mkdir ${BUILDDIR} \033[0m"
    else
      echo "[+] BuildDir: ${BUILDDIR}"      
  fi 
}

##############################################
# Name            :
# Description     :
# Returns         :
##############################################

function NeedsDir(){
  NEEDSDIR="build db main main/tmp include" 
  for dir in ${NEEDSDIR}; do
      if [ ! -d "${BUILDDIR}/${DIR}" ]; then
           echo -e '\033[1;31m [x] Missing directory: ${BUILDDIR}/${DIR} \033[0m'
	   echo -e '\033[1;33m  Hint: Create subdirs with cd $[BUILDDIR} && mkdir -p ${NEEDSDIR} \033[0m'
      fi
  done
}

