#!/bin/sh

# Include
source include/constants

##############################################
# Name            :
# Description     :
# Returns         :
##############################################
CheckUmask(){

  if [ $? -eq 0 ]; then
       echo "Usually servers can have a more strict umask like (027), where desktops may be less strict (022)."
       echo -e "${OK} [*] Setting umask: ${NORMAL}"; umask $UMASK_OPTION && echo $UMASK_OPTION
     else
       echo -e "${WARNNING} [x] Could not set umask ${NORMAL}"
  fi
}

##############################################
# Name            :
# Description     :
# Returns         :
##############################################
MyUser(){
  IM=`whoami`
  if [ "${IM}" = "root" ]; then
      echo -e "${WARNNING} [x] This programm should not be executed as root ${NORMAL}"
      exit 0
  else
      echo -e "${OK} [+] User: ${NORMAL}" ${IM}
    fi
}

##############################################
# Name            :
# Description     :
# Returns         :
##############################################
BuildDir(){
  BUILDDIR="/opt/hashId-SecScan"
  if [ ! -d ${BUILDDIR} ]; then
      echo -e "${WARNNING} [x] Directory not found: ${NORMAL}" ${BUILDDIR}
      echo -e "${WARNNING} Hint:  Missing directory, creating directory in: ${NORMAL}" ${BUILDDIR} ;sudo mkdir -p ${BUILDDIR}
    else
      echo -e "${NOTICE} [+] BuildDir found: ${NORMAL}" ${BUILDDIR}
  fi
}

##############################################
# Name            :
# Description     :
# Returns         :
##############################################
NeedsDir(){
  NEEDSDIR="include db logs"
  for DIR in ${NEEDSDIR}; do
      if [ ! -d "${BUILDDIR}/${DIR}" ]; then
           echo -e "${WARNNING} [x] Missing directory, creating directory in: ${NORMAL}" ${BUILDDIR}/${DIR}; sudo mkdir -p ${BUILDDIR}/${DIR}
        else
          echo -e "${OK} [+] SubBuildDir found: ${NORMAL}" ${BUILDDIR}/${DIR}
      fi
  done
}

##############################################
# Name            :
# Description     :
# Returns         :
##############################################
CheckIncludeFiles(){
INCLUDE_DIR="/opt/hashId-SecScan/include"
ls -A ${INCLUDE_DIR}/* &>/dev/null
       if [ $? = 0 ];then
           echo -e "${OK} [+] Files found in include directory: ${NORMAL}" ${INCLUDE_DIR}
        else
           CreateIncludeFiles
       fi
}

##############################################
# Name            :
# Description     :
# Returns         :
##############################################
CreateIncludeFiles(){
           echo -e "${WARNNING} [x] Include files wasn't found in include directory ... ${NORMAL}"
           echo -e "${OK} [+] Creating files in: ${NORMAL}" ${INCLUDE_DIR}
           sudo cp -Rfa include/{constants,functions} ${INCLUDE_DIR}
           echo -e "${NOTICE} [+] Creating alias in user environment ... ${NORMAL}";sudo echo "alias hashidsecscan='/opt/hashId-SecScan/hashidsecscan' " >> ~/.bash_alias
           echo -e "${NOTICE} [+] Enabling alias in user environment ... ${NORMAL}";source ~/.bash_alias

}
